In [2]:
import torch
import numpy as np

In [3]:
#   Load tensors directly from data
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [4]:
#   Load tensors from numpy array
array = np.array(data)
x_np = torch.from_numpy(array)
x_np

tensor([[1, 2],
        [3, 4]])

In [5]:
#   Load tensor to tensor
x_ones = torch.ones_like(x_data)
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_zeros = torch.zeros_like(x_data)
x_ones, x_rand, x_zeros

(tensor([[1, 1],
         [1, 1]]),
 tensor([[0.6345, 0.1878],
         [0.0531, 0.2739]]),
 tensor([[0, 0],
         [0, 0]]))

In [6]:
#   See the various tensor attributes (shape, datatype, device)
x_rand.shape, x_rand.dtype, x_rand.device

(torch.Size([2, 2]), torch.float32, device(type='cpu'))

In [7]:
#   Set shape of tensor
shape_tensor = (2, 3)
rand_tensor = torch.rand(shape_tensor)
rand_tensor

tensor([[0.0753, 0.7490, 0.7802],
        [0.8133, 0.6494, 0.4916]])

In [8]:
#   Move tensor to available GPU from CPU
if torch.cuda.is_available():
  rand_tensor = rand_tensor.to("cuda")

In [9]:
#   Tensor indexing (similar to numpy arrays)
tensor = torch.ones(4, 4)
print('First row: {}'.format(tensor[0]))
print('First column: {}'.format(tensor[:, 0]))
print('Last column: {}'.format(tensor[:, -1]))

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])


In [10]:
tensor[:,1] = 1
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [11]:
#   Concatenating tensors along columns (vstack)
t1 = torch.cat([tensor, tensor], dim=1)
t1

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [12]:
#   Concatenating tensors along rows (hstack)
t2 = torch.cat([tensor, tensor], dim=0)
t2

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

#   Arithmetic operations with tensors

In [13]:
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
#   Matrix multiplication
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.matmul(tensor, tensor.T)
y1, y2, y3

(tensor([[4., 4., 4., 4.],
         [4., 4., 4., 4.],
         [4., 4., 4., 4.],
         [4., 4., 4., 4.]]),
 tensor([[4., 4., 4., 4.],
         [4., 4., 4., 4.],
         [4., 4., 4., 4.],
         [4., 4., 4., 4.]]),
 tensor([[4., 4., 4., 4.],
         [4., 4., 4., 4.],
         [4., 4., 4., 4.],
         [4., 4., 4., 4.]]))

In [15]:
#   Element-wise product
z1 = tensor * tensor
z1

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [16]:
#   Sum of tensor as a single element tensor
agg = tensor.sum()

#   Convert tensor value into a numerical value
print(agg.item(), type(agg.item()))

16.0 <class 'float'>


In [17]:
#   In-place operations tore result into operand, denoted by '_' suffix
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
tensor.add_(5)
tensor

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])